version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: eslint
    versions:
    - 7.19.0
  - dependency-name: husky
    versions:
    - 4.3.8
  - dependency-name: rollup
    versions:
    - 2.38.3
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.7
  commit-message:
    prefix: build
    prefix-development: chore
